version: '3'

services:
  diagnosis-key-pg:
    build: "./docker/diagnosis-key-pg"
    ports:
      - "5434:5432"
  commons-server:
    build: "./docker/commons-server"
    depends_on:
      - "diagnosis-key-pg"
    environment:
      - COMMONS_GRPC_ADDRESS=0.0.0.0
      - COMMONS_GRPC_PORT=5000

      - COMMONS_HTTP_ADDRESS=0.0.0.0
      - COMMONS_HTTP_PORT=5001

      - COMMONS_DB_HOST=diagnosis-key-pg
      - COMMONS_DB_PORT=5432
      - COMMONS_DB_DATABASE=covid19
      - COMMONS_DB_USER=covid19
      - COMMONS_DB_PASSWORD=covid19databasepassword
    ports:
      - "5000:5000"
      - "5001:5001"
