version: '3'

services:
  diagnosis-key-pg:
    build: "./docker/diagnosis-key-pg"
    ports:
      - "5434:5432"
    volumes:
      - "./pg-data/:/data/"
  commons-server:
    build:
      context: .
      dockerfile: "./docker/commons-server/Dockerfile"
    depends_on:
      - "diagnosis-key-pg"
    environment:
      - COMMONS_GRPC_ADDRESS=0.0.0.0
      - COMMONS_GRPC_PORT=5000

      - COMMONS_HTTP_ADDRESS=0.0.0.0
      - COMMONS_HTTP_PORT=5001

      - COMMONS_DB_HOST=diagnosis-key-pg
      - COMMONS_DB_PORT=5432
      - COMMONS_DB_DATABASE=covid19
      - COMMONS_DB_USER=covid19
      - COMMONS_DB_PASSWORD=covid19databasepassword
    ports:
      - "5000:5000"
      - "5001:5001"
      - "2112:2112"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - diagnosis-key-pg
      - commons-server
