# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commons.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='commons.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z\007.;proto',
  serialized_pb=b'\n\rcommons.proto\x12\x05proto\x1a\x1cgoogle/api/annotations.proto\"K\n\x06Report\x12\x19\n\x11\x61uthorization_key\x18\x01 \x01(\x0c\x12&\n\x07reports\x18\x02 \x03(\x0b\x32\x15.proto.TimestampedTEK\"[\n\rGetKeyRequest\x12\x14\n\x0c\x61uthority_id\x18\x01 \x01(\x0c\x12\x0c\n\x04\x45NIN\x18\x02 \x01(\r\x12&\n\x06hrange\x18\x03 \x01(\x0b\x32\x16.proto.HistoricalRange\"3\n\x0fHistoricalRange\x12\x12\n\nstart_date\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ys\x18\x02 \x01(\r\"}\n\x0cTokenRequest\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\x0c\x12 \n\x08key_type\x18\x02 \x01(\x0e\x32\x0e.proto.KeyType\x12\x1d\n\x15permitted_range_start\x18\x03 \x01(\t\x12\x1b\n\x13permitted_range_end\x18\x04 \x01(\t\"9\n\rTokenResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12\x19\n\x11\x61uthorization_key\x18\x02 \x01(\x0c\"\"\n\x11\x41\x64\x64ReportResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t\"O\n\x17GetDiagnosisKeyResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12%\n\x06record\x18\x02 \x01(\x0b\x32\x15.proto.TimestampedTEK\"+\n\x0eTimestampedTEK\x12\x0b\n\x03TEK\x18\x01 \x01(\x0c\x12\x0c\n\x04\x45NIN\x18\x02 \x01(\r*%\n\x07KeyType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\r\n\tDIAGNOSED\x10\x01\x32\xd7\x02\n\x0b\x44iagnosisDB\x12Y\n\tAddReport\x12\r.proto.Report\x1a\x18.proto.AddReportResponse\"#\x82\xd3\xe4\x93\x02\x1d\"\x18/v1/diagnosis/add_report:\x01*\x12w\n\x10GetDiagnosisKeys\x12\x14.proto.GetKeyRequest\x1a\x1e.proto.GetDiagnosisKeyResponse\"+\x82\xd3\xe4\x93\x02%\" /v1/diagnosis/get_diagnosis_keys:\x01*0\x01\x12t\n\x15GetAuthorizationToken\x12\x13.proto.TokenRequest\x1a\x14.proto.TokenResponse\"0\x82\xd3\xe4\x93\x02*\"%/v1/diagnosis/get_authorization_token:\x01*B\tZ\x07.;protob\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])

_KEYTYPE = _descriptor.EnumDescriptor(
  name='KeyType',
  full_name='proto.KeyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIAGNOSED', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=625,
  serialized_end=662,
)
_sym_db.RegisterEnumDescriptor(_KEYTYPE)

KeyType = enum_type_wrapper.EnumTypeWrapper(_KEYTYPE)
UNKNOWN = 0
DIAGNOSED = 1



_REPORT = _descriptor.Descriptor(
  name='Report',
  full_name='proto.Report',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='authorization_key', full_name='proto.Report.authorization_key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reports', full_name='proto.Report.reports', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=129,
)


_GETKEYREQUEST = _descriptor.Descriptor(
  name='GetKeyRequest',
  full_name='proto.GetKeyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='authority_id', full_name='proto.GetKeyRequest.authority_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ENIN', full_name='proto.GetKeyRequest.ENIN', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hrange', full_name='proto.GetKeyRequest.hrange', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=222,
)


_HISTORICALRANGE = _descriptor.Descriptor(
  name='HistoricalRange',
  full_name='proto.HistoricalRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_date', full_name='proto.HistoricalRange.start_date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='days', full_name='proto.HistoricalRange.days', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=275,
)


_TOKENREQUEST = _descriptor.Descriptor(
  name='TokenRequest',
  full_name='proto.TokenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='api_key', full_name='proto.TokenRequest.api_key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key_type', full_name='proto.TokenRequest.key_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='permitted_range_start', full_name='proto.TokenRequest.permitted_range_start', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='permitted_range_end', full_name='proto.TokenRequest.permitted_range_end', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=402,
)


_TOKENRESPONSE = _descriptor.Descriptor(
  name='TokenResponse',
  full_name='proto.TokenResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='proto.TokenResponse.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authorization_key', full_name='proto.TokenResponse.authorization_key', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=461,
)


_ADDREPORTRESPONSE = _descriptor.Descriptor(
  name='AddReportResponse',
  full_name='proto.AddReportResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='proto.AddReportResponse.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=463,
  serialized_end=497,
)


_GETDIAGNOSISKEYRESPONSE = _descriptor.Descriptor(
  name='GetDiagnosisKeyResponse',
  full_name='proto.GetDiagnosisKeyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='proto.GetDiagnosisKeyResponse.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='record', full_name='proto.GetDiagnosisKeyResponse.record', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=499,
  serialized_end=578,
)


_TIMESTAMPEDTEK = _descriptor.Descriptor(
  name='TimestampedTEK',
  full_name='proto.TimestampedTEK',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='TEK', full_name='proto.TimestampedTEK.TEK', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ENIN', full_name='proto.TimestampedTEK.ENIN', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=580,
  serialized_end=623,
)

_REPORT.fields_by_name['reports'].message_type = _TIMESTAMPEDTEK
_GETKEYREQUEST.fields_by_name['hrange'].message_type = _HISTORICALRANGE
_TOKENREQUEST.fields_by_name['key_type'].enum_type = _KEYTYPE
_GETDIAGNOSISKEYRESPONSE.fields_by_name['record'].message_type = _TIMESTAMPEDTEK
DESCRIPTOR.message_types_by_name['Report'] = _REPORT
DESCRIPTOR.message_types_by_name['GetKeyRequest'] = _GETKEYREQUEST
DESCRIPTOR.message_types_by_name['HistoricalRange'] = _HISTORICALRANGE
DESCRIPTOR.message_types_by_name['TokenRequest'] = _TOKENREQUEST
DESCRIPTOR.message_types_by_name['TokenResponse'] = _TOKENRESPONSE
DESCRIPTOR.message_types_by_name['AddReportResponse'] = _ADDREPORTRESPONSE
DESCRIPTOR.message_types_by_name['GetDiagnosisKeyResponse'] = _GETDIAGNOSISKEYRESPONSE
DESCRIPTOR.message_types_by_name['TimestampedTEK'] = _TIMESTAMPEDTEK
DESCRIPTOR.enum_types_by_name['KeyType'] = _KEYTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Report = _reflection.GeneratedProtocolMessageType('Report', (_message.Message,), {
  'DESCRIPTOR' : _REPORT,
  '__module__' : 'commons_pb2'
  # @@protoc_insertion_point(class_scope:proto.Report)
  })
_sym_db.RegisterMessage(Report)

GetKeyRequest = _reflection.GeneratedProtocolMessageType('GetKeyRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETKEYREQUEST,
  '__module__' : 'commons_pb2'
  # @@protoc_insertion_point(class_scope:proto.GetKeyRequest)
  })
_sym_db.RegisterMessage(GetKeyRequest)

HistoricalRange = _reflection.GeneratedProtocolMessageType('HistoricalRange', (_message.Message,), {
  'DESCRIPTOR' : _HISTORICALRANGE,
  '__module__' : 'commons_pb2'
  # @@protoc_insertion_point(class_scope:proto.HistoricalRange)
  })
_sym_db.RegisterMessage(HistoricalRange)

TokenRequest = _reflection.GeneratedProtocolMessageType('TokenRequest', (_message.Message,), {
  'DESCRIPTOR' : _TOKENREQUEST,
  '__module__' : 'commons_pb2'
  # @@protoc_insertion_point(class_scope:proto.TokenRequest)
  })
_sym_db.RegisterMessage(TokenRequest)

TokenResponse = _reflection.GeneratedProtocolMessageType('TokenResponse', (_message.Message,), {
  'DESCRIPTOR' : _TOKENRESPONSE,
  '__module__' : 'commons_pb2'
  # @@protoc_insertion_point(class_scope:proto.TokenResponse)
  })
_sym_db.RegisterMessage(TokenResponse)

AddReportResponse = _reflection.GeneratedProtocolMessageType('AddReportResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDREPORTRESPONSE,
  '__module__' : 'commons_pb2'
  # @@protoc_insertion_point(class_scope:proto.AddReportResponse)
  })
_sym_db.RegisterMessage(AddReportResponse)

GetDiagnosisKeyResponse = _reflection.GeneratedProtocolMessageType('GetDiagnosisKeyResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETDIAGNOSISKEYRESPONSE,
  '__module__' : 'commons_pb2'
  # @@protoc_insertion_point(class_scope:proto.GetDiagnosisKeyResponse)
  })
_sym_db.RegisterMessage(GetDiagnosisKeyResponse)

TimestampedTEK = _reflection.GeneratedProtocolMessageType('TimestampedTEK', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTAMPEDTEK,
  '__module__' : 'commons_pb2'
  # @@protoc_insertion_point(class_scope:proto.TimestampedTEK)
  })
_sym_db.RegisterMessage(TimestampedTEK)


DESCRIPTOR._options = None

_DIAGNOSISDB = _descriptor.ServiceDescriptor(
  name='DiagnosisDB',
  full_name='proto.DiagnosisDB',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=665,
  serialized_end=1008,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddReport',
    full_name='proto.DiagnosisDB.AddReport',
    index=0,
    containing_service=None,
    input_type=_REPORT,
    output_type=_ADDREPORTRESPONSE,
    serialized_options=b'\202\323\344\223\002\035\"\030/v1/diagnosis/add_report:\001*',
  ),
  _descriptor.MethodDescriptor(
    name='GetDiagnosisKeys',
    full_name='proto.DiagnosisDB.GetDiagnosisKeys',
    index=1,
    containing_service=None,
    input_type=_GETKEYREQUEST,
    output_type=_GETDIAGNOSISKEYRESPONSE,
    serialized_options=b'\202\323\344\223\002%\" /v1/diagnosis/get_diagnosis_keys:\001*',
  ),
  _descriptor.MethodDescriptor(
    name='GetAuthorizationToken',
    full_name='proto.DiagnosisDB.GetAuthorizationToken',
    index=2,
    containing_service=None,
    input_type=_TOKENREQUEST,
    output_type=_TOKENRESPONSE,
    serialized_options=b'\202\323\344\223\002*\"%/v1/diagnosis/get_authorization_token:\001*',
  ),
])
_sym_db.RegisterServiceDescriptor(_DIAGNOSISDB)

DESCRIPTOR.services_by_name['DiagnosisDB'] = _DIAGNOSISDB

# @@protoc_insertion_point(module_scope)
