- name: Check required packages
  become: yes
  package:
    name: [docker.io, python3, python3-pip]
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Install docker-compose for python
  become: yes
  pip:
    name: docker-compose

- name: Ensure docker service is started and enabled
  become: yes
  service:
    name: docker
    state: started
    enabled: yes
